# Generated by Django 3.1.6 on 2021-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='condition',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
