# Generated by Django 3.1.6 on 2021-02-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('country', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=16)),
                ('native_language', models.CharField(max_length=32)),
            ],
        ),
    ]
