# Generated by Django 3.1.6 on 2021-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210211_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
