# Generated by Django 3.1.6 on 2021-03-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_requestbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In progress'), (2, 'Confirmed '), (3, 'Rejected'), (4, 'Sent via mail service'), (5, 'Received Book'), (6, 'Sent back'), (7, 'Received Book (Final)')]),
        ),
    ]
