# Generated by Django 3.1.6 on 2021-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210319_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbook',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(10, 'In progress'), (20, 'Confirmed '), (30, 'Rejected'), (40, 'Sent via mail service'), (50, 'Received Book'), (60, 'Sent back'), (70, 'Received Book (Final)')]),
        ),
    ]
