# Generated by Django 3.1.6 on 2021-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20210322_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(default=True, null=True, upload_to='covers'),
        ),
    ]
